[package]
name = "grade-school-multiplication-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rug]
rug = "1.16"
default-features = false
features = ["integer"]